# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d8e0cd5c4d9c5b9708adace857e875f5b174b61616bd2248501db388ce2b58e6ba298ff2f093b5cbe4c75e5caca0b5d3a717f4b3c9463efca707b2ea80f93b8

test:
  secret_key_base: b29598a8cb34a97bc69fd7eac1ca93447fb9816350c6576be85bc655bc80f79024910dc64cae72b118c73a11887f9afa791fd3bfe13b002b658a959314be9bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
